version: '3.8'

services:
  dicedb:
    image: dicedb/dicedb:latest
    ports:
      - "7379:7379"

  backend:
    build:
      context: .
      dockerfile: PlaygroundMonoDockerfile  
    ports:
      - "8080:8080"
    depends_on:
      - dicedb
    environment:
      - DICE_ADDR=dicedb:7379

  frontend:
    build:
      context: ../../
      dockerfile: ./apps/playground-web/Dockerfile.dev  
    ports:
      - "3000:3000"               
    volumes:
      - .:/app                    # Mount the entire project directory to /app inside the container
      - /app/node_modules          # Prevent overwriting node_modules inside the container
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
