FROM node:20-slim AS base
RUN corepack enable
RUN corepack prepare yarn@4.5.1 --activate

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN --mount=type=cache,target=/usr/src/app/.yarn/cache \
    yarn install --immutable
RUN yarn run -r build
RUN yarn workspace playground-web pack --out-dir /prod/playground-web

FROM base 
COPY --from=build /prod/playground-web /prod/playground-web
WORKDIR /prod/playground-web
EXPOSE 3000
CMD [ "yarn", "dev" ]
